[package]
name = "bevy_locomotion"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
# For vector math and transformations
glam = "0.27.0"
# For more advanced math operations we might need
nalgebra = "0.32.3"
